name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Vulnerability scan
        uses: wetransform/gha-trivy@v3.0.0
    